// <auto-generated />
namespace UNiVERSiTYwebapp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class version10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version10));
        
        string IMigrationMetadata.Id
        {
            get { return "201705111357591_version.1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
